---
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: traefik
      no_create_home: true
      shell: /bin/false
      uid: ${traefik_id}
      no_user_group: true
      primary_group: isolated
      groups:
        - docker
        - isolated

storage:
  directories:
    - path: "/etc/docker/compose/traefik"
      mode: 0750
      user:
        name: traefik
      group:
        name: isolated
    - path: "/srv/traefik"
      mode: 0750
      user:
        name: traefik
      group:
        name: isolated
    - path: "/srv/traefik/letsencrypt"
      mode: 0750
      user:
        name: traefik
      group:
        name: isolated

  files:
    - path: "/etc/docker/compose/traefik/docker-compose.yml"
      mode: 0640
      user:
        name: traefik
      group:
        name: isolated
      contents:
        inline: |-
          version: "3.9"
          services:
            traefik:
              image: traefik:v2.6
              container_name: traefik
              privileged: true
              user: "${traefik_id}:$${DOCKER_GROUP_ID}"
              ports:
                - 80:80
                - 443:443
                - 8080:8080
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock:ro
                - /srv/traefik/letsencrypt:/letsencrypt:z
              command:
                - "--api.insecure=true"
                - "--providers.docker"
                - "--providers.docker.exposedbydefault=false"
                - "--providers.docker.network=traefik"
                - "--entrypoints.web.address=:80"
                - "--entrypoints.websecure.address=:443"
                - "--providers.docker.defaultRule=Host(`{{ normalize .Name }}.${domain_name}`)"
                - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
                - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=cloudflare"
                - "--certificatesresolvers.mydnschallenge.acme.email=postmaster@${domain_name}"
                - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"
                - "--serverstransport.forwardingtimeouts.idleconntimeout=10"
              labels:
                # https://traefik.io/blog/traefik-2-0-docker-101-fc2893944b9d/
                # middleware redirect
                - "traefik.enable=true"
                - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

                # global redirect to https
                - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
                - "traefik.http.routers.redirs.entrypoints=web"
                - "traefik.http.routers.redirs.middlewares=redirect-to-https"

                # global middle wares
                - "traefik.http.middlewares.our-slash.chain.middlewares=strip-prefix-1,strip-prefix-2"
                - "traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
                - "traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$$${1}/"
                - "traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true"
                - "traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+"

                # router for traefik dsahboard
                - "traefik.http.routers.traefik.rule=Host(`${hostname}.${domain_name}`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))"
                - "traefik.http.middlewares.traefik-stripprefix.stripprefix.prefixes=/traefik"
                - "traefik.http.routers.traefik.middlewares=traefik-stripprefix"
                - "traefik.http.routers.traefik.entrypoints=websecure"
                - "traefik.http.routers.traefik.service=api@internal"
                - "traefik.http.routers.traefik.tls.certresolver=mydnschallenge"
              environment:
                - "CF_DNS_API_TOKEN=${cf_dns_api_token}"
              networks:
                - traefik
          networks:
            traefik:
              external: true
systemd:
  units:
    - name: docker-compose@traefik.service
      enabled: true
      dropins:
        - name: traefik-net-perms.conf
          contents: |-
            [Service]
            CapabilityBoundingSet=CAP_NET_BIND_SERVICE
            AmbientCapabilities=CAP_NET_BIND_SERVICE
